CC       = gcc
CFLAGS   = -O2 -g

read_mill2_snapshot_file:	read_mill2_snapshot_file.o
	$(CC) $(CFLAGS) read_mill2_snapshot_file.o -o read_mill2_snapshot_file

clean:
	\rm -rf *.o read_mill2_snapshot_file
