# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install -y -q python3-h5py-mpi
        python -m pip install --upgrade pip
        pip install pytest pytest-mpi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Single process test
      run: |
        mpirun --oversubscribe -np 1 python3 -m pytest --with-mpi
    - name: Two process test
      run: |
        mpirun --oversubscribe -np 2 python3 -m pytest --with-mpi
    - name: Three process test
      run: |
        mpirun --oversubscribe -np 3 python3 -m pytest --with-mpi
    - name: Four process test
      run: |
        mpirun --oversubscribe -np 4 python3 -m pytest --with-mpi
    - name: Eight process test
      run: |
        mpirun --oversubscribe -np 8 python3 -m pytest --with-mpi
